version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./pylearn.db
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - APP_URL=http://localhost:8000
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app/backend
      - pylearn-db:/app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  pylearn-db:

